server:
  port: 10080
spring:
  application:
    name: member-service-consumer #名称，可以自己指定
    #    配置链路追踪zipkin+sleuth
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率在 0-1 之间，1 表示全部采集
      probability: 1


#eureka 客户端配置
eureka:
  client:
    register-with-eureka: true #将自己注册到 EurekaServer
    fetchRegistry: true
    service-url: #表示将自己注册到哪个 EurekaServer
#      defaultZone: http://localhost:9001/eureka
      defaultZone: http://eureka9001.com:9001/eureka, http://eureka9002.com:9002/eureka
