server:
  port: 10008
spring:
  application:
    name: member-service-provider #名称，可以自己指定
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/e_commerce_center_db?userSSL=true;userUnicode=true;characterEncoding=UTF-8
    username: root
    password: 123456
mybatis:
  mapperLocations: classpath:mapper/*.xml #后面 mapper 文件的位置
  type-aliases-package: com.lilystu.springcloud.entity # 实体类的包路径