server:
  port: 10008
spring:
  application:
    name: member-service-provider-10008 #名称，可以自己指定
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/e_commerce_center_db?userSSL=true;userUnicode=true;characterEncoding=UTF-8
    username: root
    password: 123456
mybatis:
  mapperLocations: classpath:mapper/*.xml #后面 mapper 文件的位置
  type-aliases-package: com.lilystu.springcloud.entity # 实体类的包路径

#eureka 客户端配置
eureka:
  client:
    register-with-eureka: true #将自己注册到 EurekaServer
    #是否从从 EurekaServer 抓取注册信息，
    #默认为 true, 单节点无所谓，
    #集群必须设置为 true 才能配合 ribbon 使用负载均衡
    fetchRegistry: true
    service-url: #表示将自己注册到哪个 EurekaServer
        defaultZone: http://localhost:9001/eureka
#  instance: #配合eureka禁用自我保护机制
#    lease-renewal-interval-in-seconds: 1 #发送心跳间隔时间：秒
#    lease-expiration-duration-in-seconds: 2 #服务端收到最后一次心跳的等待时间上线：秒，超时将剔除该服务