spring:
  web:
    resources:
      static-locations:
#      ["classpath:/META-INF/resources/", "classpath:/resources/", "classpath:/static/", "classpath:/public/","classpath:/lily/"]
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
        - classpath:/lily/
#       配置过滤器,开启Rest请求功能
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#        配置视图解析器
    view:
      suffix: .html
      prefix: /lily/ #注意静态资源访问前缀要加上
    contentnegotiation:
      favor-parameter: true #启用基于请求参数的内容协商功能
