server:
  port: 80
spring:
  application:
    name: member-service-nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080 #这个是 sentinel 控制台(sentinel dashboard)的地址
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: '*'
#openfeign 和 sentinel 整合，必须配
feign:
  sentinel:
    enabled: true