#修改最大上传文件大小
spring:
  servlet:
    multipart:
      max-file-size: 5MB  #默认1Mb
      max-request-size: 20MB  #默认10Mb
#server:
#  port: 10001
#  tomcat: #配置Tomcat
#    threads:
#      max: 10 #最大工作线程数，默认200
#      min-spare: #最小工作线程数，默认10
#    accept-count: 200 #tomcat启动线程数达到最大值后，允许排队的最大线程数
#    max-connections: 2000 #最大连接数，并发数
#    connection-timeout: 10000 #建立连接的超时时间，单位ms
#    #。。。