#修改最大上传文件大小
spring:
  servlet:
    multipart:
      max-file-size: 5MB  #默认1Mb
      max-request-size: 20MB  #默认10Mb
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot?userSSL=true&amp;userUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#    配置druid
    druid:
      stat-view-servlet: #开启druid页面监控功能
        enabled: true
        login-username: lily
        login-password: 666
        reset-enable: false
      web-stat-filter: #配置web监控
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      filter:
        wall: #配置sql防火墙
          config:
            drop-table-allow: false
            select-all-column-allow: false
          enabled: true
#server:
#  port: 10001
#  tomcat: #配置Tomcat
#    threads:
#      max: 10 #最大工作线程数，默认200
#      min-spare: #最小工作线程数，默认10
#    accept-count: 200 #tomcat启动线程数达到最大值后，允许排队的最大线程数
#    max-connections: 2000 #最大连接数，并发数
#    connection-timeout: 10000 #建立连接的超时时间，单位ms
#    #。。。

#配置数据源